package com.anbui.yum.presentation.cart

import com.anbui.yum.domain.model.ShoppingList

data class CartUiState(
    val tabState: Int = 0,
    val isBottomSheetOpen: Boolean = false,
    val hmItems: List<ShoppingList> = listOf(
        ShoppingList(
            id = "1",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef1",
            categoriesName = "Baking & Cooking",
        ),
        ShoppingList(
            id = "2",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef2",
            categoriesName = "Baking & Cooking",
        ),
        ShoppingList(
            id = "3",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef3",
            categoriesName = "Baking & Cooking",
        ),
        ShoppingList(
            id = "4",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef4",
            categoriesName = "Baking & Cooking",
        ),
        ShoppingList(
            id = "5",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef5",
            categoriesName = "Baking & Cooking",
        ),
        ShoppingList(
            id = "6",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Baking & Cooking",
        ),
        ShoppingList(
            id = "7",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef6",
            categoriesName = "Baking & Cooking",
        ),
        ShoppingList(
            id = "8",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "9",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "10",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "11",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "12",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "13",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "14",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "15",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "16",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "17",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "18",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "19",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "20",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "21",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "22",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "23",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "24",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "25",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "26",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "27",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "28",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "29",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "30",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "31",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "32",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "33",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),
        ShoppingList(
            id = "34",
            amount = 1,
            foodName = "Pepper",
            recipeName = "Weeknight beef",
            categoriesName = "Breakfast",
        ),

        ),
)
